const dataset = [
  {
    title: "Atcoder",
    slug: "atcoder",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/atcoder.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Codeforces",
    slug: "codeforces",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/codeforces.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Codechef",
    slug: "codechef",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/codechef.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "CoderByte",
    slug: "coderbyte",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/coderbyte.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Codewars",
    slug: "codewars",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/codewars.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Codecademy",
    slug: "codecademy",
    addedBy: "SUMITHSAI",
    cardImagePath: "./RandomSize/codecademy.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "FreeCodeCamp",
    slug: "freeCodeCamp",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/freeCodeCamp.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "GeeksforGeeks",
    slug: "geeksforgeeks",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/geeksforgeeks.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "HackerEarth",
    slug: "hackerearth",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/hackerearth.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "HackerRank",
    slug: "hackerrank",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/hackerrank.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "ICPC",
    slug: "icpc",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/icpc.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "LeetCode",
    slug: "leetcode",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/leetcode.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "SPOJ",
    slug: "spoj",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/spoj.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Topcoder",
    slug: "topcoder",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/topcoder.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
  {
    title: "Toph",
    slug: "toph",
    addedBy: "Shariar-Hasan",
    cardImagePath: "./RandomSize/toph.png",
    sizes: [
      { title: "16×16", folderPath: "./16/", format: "png" },
      { title: "24×24", folderPath: "./24/", format: "png" },
      { title: "32×32", folderPath: "./32/", format: "png" },
      { title: "48×48", folderPath: "./48/", format: "png" },
      { title: "64×64", folderPath: "./64/", format: "png" },
      { title: "96×96", folderPath: "./96/", format: "png" },
      { title: "128×128", folderPath: "./128/", format: "png" },
      { title: "Random Size", folderPath: "./RandomSize/", format: "png" },
    ],
  },
];
